import {
    Activity,
    Archive,
    ArrowLeft,
    Bell,
    BellRing,
    CalendarDays,
    Check,
    ChevronRight,
    CircleAlert,
    CircleCheck,
    ClipboardList,
    Clock3,
    Copy,
    Database,
    Download,
    Eye,
    FileCode2,
    FileText,
    Filter,
    Gauge,
    History,
    Inbox,
    KeyRound,
    LayoutDashboard,
    Lightbulb,
    LogOut,
    Mail,
    Menu,
    MessageSquareText,
    Moon,
    Play,
    PanelLeftClose,
    PanelLeftOpen,
    Plus,
    RefreshCw,
    Search,
    Send,
    Settings,
    Shield,
    ShieldAlert,
    SlidersHorizontal,
    Sparkles,
    Sun,
    Trash2,
    Trophy,
    Upload,
    UserCog,
    Users,
    X,
    createIcons,
} from 'lucide';

const icons = {
    Activity, Archive, ArrowLeft, Bell, BellRing, CalendarDays, Check, ChevronRight,
    CircleAlert, CircleCheck, ClipboardList, Clock3, Copy, Database, Download, Eye,
    FileCode2, FileText, Filter, Gauge, History, Inbox, KeyRound, LayoutDashboard, Lightbulb,
    LogOut, Mail, Menu, MessageSquareText, Moon, Play, PanelLeftClose, PanelLeftOpen, Plus, RefreshCw, Search, Send,
    Settings, Shield, ShieldAlert, SlidersHorizontal, Sparkles, Sun, Trash2, Trophy, Upload,
    UserCog, Users, X,
};

export function refreshIcons(root = document) {
    createIcons({ icons, root, inTemplates: true });
}
